name: Build ruleset

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download sing-box
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        bash <(curl -fsSL https://sing-box.app/deb-install.sh)

    - name: Compile ruleset
      run: |
        sing-box rule-set compile --output custom.srs custom.json

    - name: set NOW
      run: |
        echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        tag_name: ${{ env.NOW }}
        release_name: Release ${{ env.NOW }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./custom.srs
        asset_name: custom.srs
        asset_content_type: application/octet-stream
